import Head from 'next/head'
import HeroSection from '@/components/HeroSection';
import Navbar from '@/components/Navbar';
import AboutSection from '@/components/AboutSection'
import ProjectsSection from '@/components/ProjectsSection';
import Foooter from '@/components/Foooter';


export default function Home() {

  return (
    <div>
      <div className='bg-no-repeat bg-cover custom-img'>
        <Head>
          <title>Victor Hugo Portifolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico.png" />
        </Head>
        
        <main className='bg-yellow-200/60 z-[2] px-10 md:px-20 lg:px-40 dark:bg-gray-900/80'>
          <section className="min-h-screen" >
            <Navbar />
            <HeroSection />
            <AboutSection />
            <ProjectsSection />
            <Foooter />
          </section>          
        </main>
      </div>
    </div>
  );
}